///////////////////////////////////////////////////////////
//  ActionExecutionSpecification.cs
//  Implementation of the Class ActionExecutionSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:25
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
//using UML.Actions; // TODO
namespace UML.Interactions {
	/// <summary>
	/// An ActionExecutionSpecification is a kind of ExecutionSpecification
	/// representing the execution of an Action.
	/// </summary>
	public class ActionExecutionSpecification : ExecutionSpecification {

		/// <summary>
		/// Action whose execution is occurring.
		/// </summary>
		//public UML.Actions.Action action; // TODO

        public ActionExecutionSpecification(){

		}

		~ActionExecutionSpecification(){

		}

	}//end ActionExecutionSpecification

}//end namespace Interactions