///////////////////////////////////////////////////////////
//  BehaviorExecutionSpecification.cs
//  Implementation of the Class BehaviorExecutionSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:26
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
//using UML.CommonBehavior; // TODO
namespace UML.Interactions {
	/// <summary>
	/// A BehaviorExecutionSpecification is a kind of ExecutionSpecification
	/// representing the execution of a Behavior.
	/// </summary>
	public class BehaviorExecutionSpecification : ExecutionSpecification {

		/// <summary>
		/// Behavior whose execution is occurring.
		/// </summary>
		//public UML.CommonBehavior.Behavior behavior; // TODO

        public BehaviorExecutionSpecification(){

		}

		~BehaviorExecutionSpecification(){

		}

	}//end BehaviorExecutionSpecification

}//end namespace Interactions