///////////////////////////////////////////////////////////
//  ConsiderIgnoreFragment.cs
//  Implementation of the Class ConsiderIgnoreFragment
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:28
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
using UML.CommonStructure;
namespace UML.Interactions {
	/// <summary>
	/// A ConsiderIgnoreFragment is a kind of CombinedFragment that is used for the
	/// consider and ignore cases, which require lists of pertinent Messages to be
	/// specified.
	/// </summary>
	public class ConsiderIgnoreFragment : CombinedFragment {

		/// <summary>
		/// The set of messages that apply to this fragment.
		/// </summary>
	    //public readonly LinkedList<UML.CommonStructure.NamedElement> message = new LinkedList<UML.CommonStructure.NamedElement>(); //TODO

        public ConsiderIgnoreFragment(){

		}

		~ConsiderIgnoreFragment(){

		}

	}//end ConsiderIgnoreFragment

}//end namespace Interactions