///////////////////////////////////////////////////////////
//  DestructionOccurrenceSpecification.cs
//  Implementation of the Class DestructionOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:29
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// A DestructionOccurenceSpecification models the destruction of an object.
	/// </summary>
	public class DestructionOccurrenceSpecification : MessageOccurrenceSpecification {

		public DestructionOccurrenceSpecification(){

		}

		~DestructionOccurrenceSpecification(){

		}

	}//end DestructionOccurrenceSpecification

}//end namespace Interactions