///////////////////////////////////////////////////////////
//  ExecutionOccurrenceSpecification.cs
//  Implementation of the Class ExecutionOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:30
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// An ExecutionOccurrenceSpecification represents moments in time at which Actions
	/// or Behaviors start or finish.
	/// </summary>
	public class ExecutionOccurrenceSpecification : OccurrenceSpecification {

		/// <summary>
		/// References the execution specification describing the execution that is started
		/// or finished at this execution event.
		/// </summary>
		public UML.Interactions.ExecutionSpecification execution;

		public ExecutionOccurrenceSpecification(){

		}

		~ExecutionOccurrenceSpecification(){

		}

	}//end ExecutionOccurrenceSpecification

}//end namespace Interactions