///////////////////////////////////////////////////////////
//  ExecutionSpecification.cs
//  Implementation of the Class ExecutionSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:30
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// An ExecutionSpecification is a specification of the execution of a unit of
	/// Behavior or Action within the Lifeline. The duration of an
	/// ExecutionSpecification is represented by two OccurrenceSpecifications, the
	/// start OccurrenceSpecification and the finish OccurrenceSpecification.
	/// </summary>
	public abstract class ExecutionSpecification : InteractionFragment {

		/// <summary>
		/// References the OccurrenceSpecification that designates the start of the Action
		/// or Behavior.
		/// </summary>
		public UML.Interactions.OccurrenceSpecification start;
		/// <summary>
		/// References the OccurrenceSpecification that designates the finish of the Action
		/// or Behavior.
		/// </summary>
		public UML.Interactions.OccurrenceSpecification finish;

		public ExecutionSpecification(){

		}

		~ExecutionSpecification(){

		}

	}//end ExecutionSpecification

}//end namespace Interactions