///////////////////////////////////////////////////////////
//  InteractionOperand.cs
//  Implementation of the Class InteractionOperand
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:31
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
using UML.CommonStructure;
namespace UML.Interactions {
    /// <summary>
    /// An InteractionOperand is contained in a CombinedFragment. An InteractionOperand
    /// represents one operand of the expression given by the enclosing
    /// CombinedFragment.
    /// </summary>
    public class InteractionOperand : InteractionFragment /*, Namespace*/ { //TODO

        /// <summary>
        /// The fragments of the operand.
        /// </summary>
        public readonly LinkedList<UML.Interactions.InteractionFragment> fragment = new LinkedList<UML.Interactions.InteractionFragment>();
		/// <summary>
		/// Constraint of the operand.
		/// </summary>
		public UML.Interactions.InteractionConstraint guard;

		public InteractionOperand(){

		}

		~InteractionOperand(){

		}

        public override string XmiType() { return "uml:InteractionOperand"; }

    }//end InteractionOperand

}//end namespace Interactions