///////////////////////////////////////////////////////////
//  InteractionConstraint.cs
//  Implementation of the Class InteractionConstraint
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:31
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



//using UML.Values; // TODO
using UML.CommonStructure;
namespace UML.Interactions {
	/// <summary>
	/// An InteractionConstraint is a Boolean expression that guards an operand in a
	/// CombinedFragment.
	/// </summary>
	public class InteractionConstraint : UML.CommonStructure.Constraint {

        /// <summary>
        /// The minimum number of iterations of a loop
        /// </summary>
        //public UML.Values.ValueSpecification minint; // TODO
        /// <summary>
        /// The maximum number of iterations of a loop
        /// </summary>
        //public UML.Values.ValueSpecification maxint; // TODO

        public InteractionConstraint(){

		}

		~InteractionConstraint(){

		}

        public override string XmiType() { return "uml:InteractionConstraint"; }

    }//end InteractionConstraint

}//end namespace Interactions