///////////////////////////////////////////////////////////
//  InteractionFragment.cs
//  Implementation of the Class InteractionFragment
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:31
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
using UML.CommonStructure;
namespace UML.Interactions {
    /// <summary>
    /// InteractionFragment is an abstract notion of the most general interaction unit.
    /// An InteractionFragment is a piece of an Interaction. Each InteractionFragment
    /// is conceptually like an Interaction by itself.
    /// </summary>
    public abstract class InteractionFragment : Element /*: NamedElement*/ { //TODO

        /// <summary>
        /// References the Lifelines that the InteractionFragment involves.
        /// </summary>
        /// public readonly LinkedList<UML.Interactions.Message> message = new LinkedList<UML.Interactions.Message>();
        public readonly List<UML.Interactions.Lifeline> covered = new List<UML.Interactions.Lifeline>();
        /// <summary>
        /// The general ordering relationships contained in this fragment.
        /// </summary>
        public readonly List<UML.Interactions.GeneralOrdering> generalOrdering = new List<UML.Interactions.GeneralOrdering>();
        /// <summary>
        /// The Interaction enclosing this InteractionFragment.
        /// </summary>
        public UML.Interactions.Interaction enclosingInteraction;
        /// <summary>
        /// The operand enclosing this InteractionFragment (they may nest recursively).
        /// </summary>
        public UML.Interactions.InteractionOperand enclosingOperand;

		public InteractionFragment(){

		}

		~InteractionFragment(){

		}

	}//end InteractionFragment

}//end namespace Interactions