///////////////////////////////////////////////////////////
//  Lifeline.cs
//  Implementation of the Class Lifeline
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:32
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



//using UML.StructuredClassifiers;  //TODO
using UML.Interactions;
//using UML.Values;                 //TODO
using UML.CommonStructure;
namespace UML.Interactions {
	/// <summary>
	/// A Lifeline represents an individual participant in the Interaction. While parts
	/// and structural features may have multiplicity greater than 1, Lifelines
	/// represent only one interacting entity.
	/// </summary>
	public class Lifeline : Element /*: NamedElement*/ { //TODO

        /// <summary>
        /// References the ConnectableElement within the classifier that contains the
        /// enclosing interaction.
        /// </summary>
        //public UML.StructuredClassifiers.ConnectableElement represents; // TODO
        /// <summary>
        /// References the Interaction that represents the decomposition.
        /// </summary>
        public UML.Interactions.PartDecomposition decomposedAs;
        /// <summary>
        /// If the referenced ConnectableElement is multivalued, then this specifies the
        /// specific individual part within that set.
        /// </summary>
        //public UML.Values.ValueSpecification selector; // TODO
        /// <summary>
        /// References the InteractionFragments in which this Lifeline takes part.
        /// </summary>
        public readonly List<UML.Interactions.InteractionFragment> coveredBy = new List<UML.Interactions.InteractionFragment>();
        /// <summary>
		/// References the Interaction enclosing this Lifeline.
		/// </summary>
        public UML.Interactions.Interaction interaction;

        public Lifeline(){

		}

		~Lifeline(){

		}

        public override string XmiType() { return "uml:Lifeline"; }

	}//end Lifeline

}//end namespace Interactions