///////////////////////////////////////////////////////////
//  MessageOccurrenceSpecification.cs
//  Implementation of the Class MessageOccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:33
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// A MessageOccurrenceSpecification specifies the occurrence of Message events,
	/// such as sending and receiving of Signals or invoking or receiving of Operation
	/// calls. A MessageOccurrenceSpecification is a kind of MessageEnd. Messages are
	/// generated either by synchronous Operation calls or asynchronous Signal sends.
	/// They are received by the execution of corresponding AcceptEventActions.
	/// </summary>
	public class MessageOccurrenceSpecification : MessageEnd/*, OccurrenceSpecification*/ { //TODO

		public MessageOccurrenceSpecification(){

		}

		~MessageOccurrenceSpecification(){

		}

	}//end MessageOccurrenceSpecification

}//end namespace Interactions