///////////////////////////////////////////////////////////
//  OccurrenceSpecification.cs
//  Implementation of the Class OccurrenceSpecification
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:34
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// An OccurrenceSpecification is the basic semantic unit of Interactions. The
	/// sequences of occurrences specified by them are the meanings of Interactions.
	/// </summary>
	public class OccurrenceSpecification : InteractionFragment {

        override public string XmiType() 
        {
            return "uml:OccurrenceSpecification";
        }

		/// <summary>
		/// References the Lifeline on which the OccurrenceSpecification appears.
		/// </summary>
		//public UML.Interactions.Lifeline covered; //TODO V buducnosti pridat kontrolu aby tento list mal prave 1 prvok.
        /// <summary>
        /// References the GeneralOrderings that specify EventOcurrences that must occur
        /// before this OccurrenceSpecification.
        /// </summary>
        public readonly LinkedList<UML.Interactions.GeneralOrdering> toBefore = new LinkedList<UML.Interactions.GeneralOrdering>();
		/// <summary>
		/// References the GeneralOrderings that specify EventOcurrences that must occur
		/// after this OccurrenceSpecification.
		/// </summary>
		public readonly LinkedList<UML.Interactions.GeneralOrdering> toAfter = new LinkedList<UML.Interactions.GeneralOrdering>();

		public OccurrenceSpecification(){

		}

		~OccurrenceSpecification(){

		}

	}//end OccurrenceSpecification

}//end namespace Interactions