///////////////////////////////////////////////////////////
//  PartDecomposition.cs
//  Implementation of the Class PartDecomposition
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:34
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
namespace UML.Interactions {
	/// <summary>
	/// A PartDecomposition is a description of the internal Interactions of one
	/// Lifeline relative to an Interaction.
	/// </summary>
	public class PartDecomposition : InteractionUse {

		public PartDecomposition(){

		}

		~PartDecomposition(){

		}

	}//end PartDecomposition

}//end namespace Interactions