///////////////////////////////////////////////////////////
//  StateInvariant.cs
//  Implementation of the Class StateInvariant
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:37
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.Interactions;
using UML.CommonStructure;
namespace UML.Interactions {
	/// <summary>
	/// A StateInvariant is a runtime constraint on the participants of the Interaction.
	/// It may be used to specify a variety of different kinds of Constraints, such as
	/// values of Attributes or Variables, internal or external States, and so on. A
	/// StateInvariant is an InteractionFragment and it is placed on a Lifeline.
	/// </summary>
	public class StateInvariant : InteractionFragment {

		/// <summary>
		/// References the Lifeline on which the StateInvariant appears.
		/// </summary>
		//public UML.Interactions.Lifeline covered; //TODO V buducnosti pridat kontrolu aby tento list mal prave 1 prvok.
        /// <summary>
        /// A Constraint that should hold at runtime for this StateInvariant.
        /// </summary>
        //public UML.CommonStructure.Constraint invariant; // TODO

        public StateInvariant(){

		}

		~StateInvariant(){

		}

	}//end StateInvariant

}//end namespace Interactions