///////////////////////////////////////////////////////////
//  Comment.cs
//  Implementation of the Class Comment
//  Generated by Enterprise Architect
//  Created on:      04-Oct-2018 16:51:27
//  Original author: Iva
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using UML.CommonStructure;
namespace UML.CommonStructure {
	/// <summary>
	/// A Comment is a textual annotation that can be attached to a set of Elements.
	/// </summary>
	public class Comment : Element {

		/// <summary>
		/// Specifies a string that is the comment.
		/// </summary>
		public string body;
		/// <summary>
		/// References the Element(s) being commented.
		/// </summary>
		public readonly LinkedList<UML.CommonStructure.Element> annotatedElement = new LinkedList<UML.CommonStructure.Element>();

		public Comment(){

		}

		~Comment(){

		}

	}//end Comment

}//end namespace CommonStructure